name: Deploy Landing Pages on Commit to Master

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
  
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Deploy HTML files to server
      run: |
     
        scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} \
          "Landing Page1.html" "Landing Page2.html" "Login Credentials.html" \
          ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:/path/to/your/web/directory

      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
