name: Deploy

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

permissions:
  contents: write  # Grant the bot permission to push changes to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Git for the deployment
      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      # Create gh-pages branch if it doesn't exist
      - name: Create gh-pages branch if it doesn't exist
        run: |
          git fetch --all
          git branch -a  
          if git show-ref --quiet refs/heads/gh-pages; then
            echo "gh-pages branch exists."
          else
            git checkout --orphan gh-pages
            git rm -rf .
            echo "Creating empty gh-pages branch."
            git commit --allow-empty -m "Initial commit to gh-pages"
          fi

      # Build and deploy (no build needed for static files, just copy)
      - name: Build and deploy
        run: |
          # For static files, this step may be empty, just pushing the files to gh-pages
          git add .
          git commit -m "Deploy to gh-pages"
          
      # Push to the gh-pages branch
      - name: Deploy to gh-pages
        run: |
          git remote set-url origin https://Gowtham563:${{ secrets.GH_TOKEN }}@github.com/Gowtham563/LoginPage.git
          git push origin gh-pages --force
