name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This gives the bot permission to push to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Create gh-pages branch if it doesn't exist
        run: |
          git fetch --all
          git branch -a  # List all branches
          if git show-ref --quiet refs/heads/gh-pages; then
            echo "gh-pages branch exists."
          else
            git checkout --orphan gh-pages
            git rm -rf .
            echo "Creating empty gh-pages branch."
            git commit --allow-empty -m "Initial commit to gh-pages"
          fi

      - name: Build and deploy
        run: |
          # Your build/deploy steps here

      - name: Deploy to gh-pages
        run: |
          git remote set-url origin https://<YOUR_USERNAME>:${{ secrets.GH_TOKEN }}@github.com/Gowtham563/LoginPage.git
          git push origin gh-pages
